export const SET_BOOKS = 'SET_BOOKS';
export const SET_MORE_BOOKS = 'SET_MORE_BOOKS';
export const SET_BOOK_ITEM = 'SET_BOOK_ITEM';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_FETCHING = 'SET_FETCHING';
export const SET_FETCHING_ITEM = 'SET_FETCHING_ITEM';